### ISSUE TITLE
heap-buffer-overflow when using many threads

### ISSUE THREAD

**Issue by Geremia** [msoos/cryptominisat#533]
I get a heap-buffer-overflow when using many threads:
```
$ cryptominisat5 --maxtime=600 -t 64 in.cnf > out.cnf
=================================================================
==54584==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603037214434 at pc 0x7fafbaa737b9 bp 0x7faf8bd1c9b0 sp 0x7faf8bd1c9a8
READ of size 1 at 0x603037214434 thread T31
    #0 0x7fafbaa737b8 in CMSat::PropEngine::propagate_any_order_fast() (/usr/lib64/libcryptominisat5.so.5.6+0x13887b8)
    #1 0x7fafbaf2655f in CMSat::lbool CMSat::Searcher::search<false>() (/usr/lib64/libcryptominisat5.so.5.6+0x183b55f)
    #2 0x7fafbae9c350 in CMSat::Searcher::solve(unsigned long, unsigned int) (/usr/lib64/libcryptominisat5.so.5.6+0x17b1350)
    #3 0x7fafbb03033a in CMSat::Solver::iterate_until_solved() (/usr/lib64/libcryptominisat5.so.5.6+0x194533a)
    #4 0x7fafbb0353ef in CMSat::Solver::solve_with_assumptions(std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > const*, bool) (/usr/lib64/libcryptominisat5.so.5.6+0x194a3ef)
    #5 0x7fafbb435def in OneThreadCalc::operator()() (/usr/lib64/libcryptominisat5.so.5.6+0x1d4adef)
    #6 0x7fafbb43b3a7 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<OneThreadCalc> > >::_M_run() (/usr/lib64/libcryptominisat5.so.5.6+0x1d503a7)
    #7 0x7fafb9386b1e  (/usr/lib64/libstdc++.so.6+0xc3b1e)
    #8 0x7fafb83f017d in start_thread (/lib64/libpthread.so.0+0x817d)
    #9 0x7fafb852e85e in __clone (/lib64/libc.so.6+0x11685e)

0x603037214434 is located 4 bytes to the right of 32-byte region [0x603037214410,0x603037214430)
allocated by thread T31 here:
    #0 0x7fafbcac2320 in __interceptor_realloc (/usr/lib64/libasan.so.5+0xec320)
    #1 0x7fafbaa910bd in CMSat::vec<CMSat::Watched>::capacity(int) (/usr/lib64/libcryptominisat5.so.5.6+0x13a60bd)

Thread T31 created by T0 here:
    #0 0x7fafbca22f50 in pthread_create (/usr/lib64/libasan.so.5+0x4cf50)
    #1 0x7fafb9386da4 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/usr/lib64/libstdc++.so.6+0xc3da4)
    #2 0x7ffcb46d4c8f  ([stack]+0x1ec8f)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/lib64/libcryptominisat5.so.5.6+0x13887b8) in CMSat::PropEngine::propagate_any_order_fast()
Shadow bytes around the buggy address:
  0x0c0686e3a830: fd fd fa fa 00 00 00 00 fa fa fd fd fd fd fa fa
  0x0c0686e3a840: 00 00 00 00 fa fa 00 00 00 00 fa fa fa fa fa fa
  0x0c0686e3a850: fa fa fd fd fd fd fa fa fd fd fd fd fa fa fa fa
  0x0c0686e3a860: fa fa fa fa 00 00 00 00 fa fa fd fd fd fd fa fa
  0x0c0686e3a870: 00 00 00 00 fa fa 00 00 00 00 fa fa 00 00 00 00
=>0x0c0686e3a880: fa fa 00 00 00 00[fa]fa 00 00 00 00 fa fa 00 00
  0x0c0686e3a890: 00 00 fa fa 00 00 00 00 fa fa 00 00 00 00 fa fa
  0x0c0686e3a8a0: 00 00 00 00 fa fa 00 00 00 00 fa fa fa fa fa fa
  0x0c0686e3a8b0: fa fa 00 00 00 00 fa fa 00 00 00 00 fa fa 00 00
  0x0c0686e3a8c0: 00 00 fa fa 00 00 00 00 fa fa 00 00 00 00 fa fa
  0x0c0686e3a8d0: 00 00 00 00 fa fa 00 00 00 00 fa fa 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==54584==ABORTING
```
```
$ cat out.cnf
c Outputting solution to console
c CryptoMiniSat version 5.6.6
c CMS Copyright Mate Soos (soos.mate@gmail.com)
c CMS SHA revision GIT-notfound
c CMS is MIT licensed
c CMS compilation env CMAKE_CXX_COMPILER = /usr/bin/c++ | CMAKE_CXX_FLAGS = -O2 -fPIC -g -fsanitize=address -fsanitize=undefined -fsanitize=leak -fno-stack-protector -Wlogical-op -Wrestrict -Wnull-dereference -Wdouble-promotion -Wshadow -Wformat=2 -Wextra-semi -pedantic -Wno-class-memaccess | COMPILE_DEFINES =  -DNDEBUG -D_FORTIFY_SOURCE=0 -DBOOST_TEST_DYN_LINK -DUSE_ZLIB | STATICCOMPILE = OFF | ONLY_SIMPLE = OFF | Boost_FOUND = 1 | STATS = OFF | SQLITE3_FOUND =  | ZLIB_FOUND = TRUE | VALGRIND_FOUND = TRUE | ENABLE_TESTING = OFF | M4RI_FOUND = FALSE | NOM4RI = OFF | SLOW_DEBUG = OFF | ENABLE_ASSERTIONS = OFF | PYTHON_EXECUTABLE = /usr/bin/python3 | PYTHON_LIBRARY = /usr/lib64/libpython3.6m.so | PYTHON_INCLUDE_DIRS = /usr/include/python3.6m | MY_TARGETS =  | LARGEMEM = OFF | LIMITMEM = OFF | compilation date time = Jan 12 2019 15:04:33
c CMS compiled with gcc version 8.2.0
c Executed with command line: cryptominisat5 --maxtime=600 -t 64 in.cnf
c Reading file 'in.cnf'
c -- clauses added: 1626118
c -- xor clauses added: 0
c -- vars added 423938
c Parsing time: 1.28 s
c   type VSIDS  rest  conf freevar  IrrL  IrrB l/longC  l/allC RedL0 RedL1 RedL2  RedB l/longC  l/allC
c [distill] long cls tried: 42/41 cl-short:42 lit-r:0 T: 0.00 T-out: N T-r: 100.00%
c [distill] long cls tried: 1353/1352 cl-short:1351 lit-r:70 T: 0.20 T-out: N T-r: 99.96%
c [distill] long cls tried: 1378/2714 cl-short:1378 lit-r:72 T: 0.46 T-out: N T-r: 99.95%
c   glue     1    79  8193  149587 1113K  490K    3.41    2.98  3214  2534  1962   457    6.99    6.71
c [distill] long cls tried: 2530/5236 cl-short:2530 lit-r:567 T: 1.28 T-out: N T-r: 99.85%
c   geom     1   147 16386  149552 1113K  490K    3.41    2.98  6928  4489  3696   594    7.84    7.62
c [distill] long cls tried: 1739/6964 cl-short:1739 lit-r:121 T: 0.69 T-out: N T-r: 99.91%
c [distill] long cls tried: 3184/10147 cl-short:3184 lit-r:880 T: 1.95 T-out: N T-r: 99.69%
c   glue     1   229   24K  149470 1113K  490K    3.41    2.98 10445  5769  7024  1234    9.22    8.86
c [distill] long cls tried: 3533/13678 cl-short:3533 lit-r:554 T: 2.15 T-out: N T-r: 99.75%
c   glue     1   276   32K  149470 1113K  490K    3.41    2.98 14349  7888  6974  1342    9.43    9.10
c [distill] long cls tried: 2986/16664 cl-short:2986 lit-r:225 T: 0.90 T-out: N T-r: 99.85%
c   glue     1   324   40K  149281 1113K  490K    3.41    2.98 18094  7452 11793  2018    9.51    9.13
```

**Comment by Geremia** [comment]
I'm thinking this was a hardware issue, as I lowered my memory clock speed and didn't run into this segfault issue anymore.

**Comment by msoos** [comment]
Oh, good to know, would have been hard to fish for this... Though I have to say that 64 threads means that the solver is actually not deterministic, so it could be that with the right "luck" you can hit this again. Let me run some ASAN tests.... I ran some with valgrind (I'm old school, I know), but I have ran many tests with ASAN, too, before, and didn't encounter issues. It's been a while. Would be nice for someone to donate a machine to fuzz on, continuously :)

**Comment by Geremia** [comment]
@Geremia I'll let you know if I run into the issue again.

**Comment by msoos** [comment]
Thank you so much!

Mate
