### ISSUE TITLE
Occasional double-free or corrupton in EGaussian destructor

### ISSUE THREAD

**Issue by maxzinkus** [msoos/cryptominisat#552]
https://github.com/msoos/cryptominisat/blob/a350e60906d9ac88add1e366aad8ea2d7679c79c/src/EGaussian.cpp#L108

I'll try to find a cnf to repro. Here's the trace:

```
*** Error in `cryptominisat5': double free or corruption (!prev): 0x0000000001d5b9b0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fae627bb7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7fae627c437a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fae627c853c]
/usr/local/lib/libcryptominisat5.so.5.6(_ZN5CMSat9EGaussianD1Ev+0xac)[0x7fae63b4076c]
/usr/local/lib/libcryptominisat5.so.5.6(_ZN5CMSat8Searcher20clearEnGaussMatrixesEv+0x298)[0x7fae63ad9548]
/usr/local/lib/libcryptominisat5.so.5.6(_ZN5CMSat6Solver20iterate_until_solvedEv+0xc4)[0x7fae63afd344]
/usr/local/lib/libcryptominisat5.so.5.6(_ZN5CMSat6Solver22solve_with_assumptionsEPKSt6vectorINS_3LitESaIS2_EEb+0x310)[0x7fae63afd880]
/usr/local/lib/libcryptominisat5.so.5.6(_Z4calcPKSt6vectorIN5CMSat3LitESaIS1_EEbPNS0_16CMSatPrivateDataEb+0x815)[0x7fae63b53205]
/usr/local/lib/libcryptominisat5.so.5.6(_ZN5CMSat9SATSolver5solveEPKSt6vectorINS_3LitESaIS2_EEb+0x5b)[0x7fae63b5339b]
cryptominisat5(_ZN4Main15multi_solutionsEv+0x72)[0x418ca2]
cryptominisat5(_ZN4Main5solveEv+0x3f0)[0x41b030]
cryptominisat5(main+0x79)[0x417829]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fae62764830]
cryptominisat5(_start+0x29)[0x4179d9]
```

**Comment by msoos** [comment]
Damn, sorry. I'll try to fuzz and fix, but if you could give me a full input CNF and output  (with GIT commit numbers, which both ScalMC and CMS output) then I'll be fixing this much faster :) Also, I invited you to the Z3 repo, please accept we can work on that together, I'll drop you a mail later today :)

**Comment by maxzinkus** [comment]
The bug'll show up again at some point, I'll have a CNFXOR file for you as soon as it does. Thank you!

**Comment by msoos** [comment]
Please don't forget to send me the full output as well -- just the CNFXOR may not be enough. Please give me the full output + the CNFXOR file + how you ran (with what options). So my bad, it's actually 3 things, not just 2 :) Otherwise, it may be impossible to reproduce. Thanks!

**Comment by maxzinkus** [comment]
Understood.

**Comment by maxzinkus** [comment]
`cryptominisat5 -t 64 input.cnf`

stdout:
```
c Outputting solution to console
c CryptoMiniSat version 5.6.8
c CMS Copyright Mate Soos (soos.mate@gmail.com)
c CMS SHA revision e069c646a9f950532d45300b5d6446e1b729cde0
c CMS is GPL licensed due to M4RI being linked. Build without M4RI to get MIT version
c Using code from 'When Boolean Satisfiability Meets Gauss-E. in a Simplex Way'
c       by C.-S. Han and J.-H. Roland Jiang in CAV 2012. Fixes by M. Soos
c CMS compilation env CMAKE_CXX_COMPILER = /usr/bin/c++ | CMAKE_CXX_FLAGS =  -mtune=native -Wall -Wextra -Wunused -Wsign-compare -fno-omit-frame-pointer -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -Wpointer-arith -Wformat-nonliteral -Winit-self -Wparentheses -Wunreachable-code -ggdb3 -Wlogical-op -Wdouble-promotion -Wshadow -Wformat=2 -pedantic | COMPILE_DEFINES =  -DUSE_GAUSS -DBOOST_TEST_DYN_LINK -DUSE_ZLIB -DUSE_M4RI | STATICCOMPILE = OFF | ONLY_SIMPLE = OFF | Boost_FOUND = 1 | STATS = OFF | SQLITE3_FOUND =  | ZLIB_FOUND = TRUE | VALGRIND_FOUND = TRUE | ENABLE_TESTING = OFF | M4RI_FOUND = TRUE | NOM4RI = OFF | SLOW_DEBUG = OFF | ENABLE_ASSERTIONS = ON | PYTHON_EXECUTABLE = /usr/bin/python2.7 | PYTHON_LIBRARY = /usr/lib/x86_64-linux-gnu/libpython2.7.so | PYTHON_INCLUDE_DIRS = /usr/include/python2.7 | MY_TARGETS =  | LARGEMEM = OFF | LIMITMEM = OFF | compilation date time = Mar 28 2019 19:00:47
c CMS compiled with gcc version 5.4.0 20160609
c Executed with command line: cryptominisat5 -t 64 CMS_error_-11.cnf
c Reading file 'CMS_error_-11.cnf'
c -- header says num vars:           5112
c -- header says num clauses:       29381
c -- clauses added: 29382
c -- xor clauses added: 1170
c -- vars added 5112
c Sampling var set contains over 100 variables, not displaying
c Sum parsing time among all threads (wall time will differ): 0.01 s
c [xor-rem-unconnected] left with 1170 xors from 1170 non-empty xors T: 0.00
c [xor-together] xored together 100 xors orig num xors: 1170 T: 0.00
c [xor-rem-unconnected] left with 1070 xors from 1070 non-empty xors T: 0.00
c [matrixfind] incrementing max number of rows to 15336
c [matrix] Good   matrix  0    110 x  118  density:  0.0%  xorlen avg:  5.19  perc sampl: 100.000 %
c [matrix] Good   matrix  1    109 x  117  density:  0.0%  xorlen avg:  5.22  perc sampl: 100.000 %
c [matrix] Good   matrix  2    109 x  110  density:  0.0%  xorlen avg:  5.22  perc sampl: 100.000 %
c [matrix] Good   matrix  3    109 x  113  density:  0.0%  xorlen avg:  5.22  perc sampl: 100.000 %
c [matrix] Good   matrix  4    108 x  114  density:  0.0%  xorlen avg:  5.25  perc sampl: 100.000 %
c [matrix] Good   matrix  5    106 x  112  density:  0.0%  xorlen avg:  5.31  perc sampl: 100.000 %
c [matrix] unused matrixes: 4
c Found matrixes: 6 from 1070 xors T: 0.00 T-out: N
c [xor-add-lem] added unit 0 bin 0 T: 0.00
c [xor-add-lem] added unit 0 bin 0 T: 0.00
c [xor-add-lem] added unit 0 bin 0 T: 0.00
c [xor-add-lem] added unit 0 bin 0 T: 0.00
c [xor-add-lem] added unit 0 bin 0 T: 0.00
c [xor-add-lem] added unit 0 bin 0 T: 0.00
```

stderr:
```
Segmentation Fault
```

[error.cnf.txt](https://github.com/msoos/cryptominisat/files/3158805/error.cnf.txt)

**Comment by cipherboy** [comment]
I can reproduce this without threads. 

On 28df9d6ba8b7a4630f5626ca65cf741b92d26e48 (via bisection) I get: 
```
c Parsing time: 0.00 s
c [xor-rem-unconnected] left with 1170 xors from 1170 non-empty xors T: 0.00
cryptominisat5: /home/cipherboy/GitHub/msoos/cryptominisat/src/xorfinder.cpp:535: bool CMSat::XorFinder::xor_together_xors(std::vector<CMSat::Xor>&): Assertion `at == 2' failed.
cryptominisat5: /home/cipherboy/GitHub/msoos/cryptominisat/src/xorfinder.cpp:535: bool CMSat::XorFinder::xor_together_xors(std::vector<CMSat::Xor>&): Assertion `at == 2' failed.
Aborted (core dumped)
134
```
(yeah, two assertions -- must be multiple threads hitting it). 

If I restart from 28df9d6ba8b7a4630f5626ca65cf741b92d26e48 and rebisect, I think the behavior was modified again in 775eab25559fd9770c073a1362cd43c83428fcb2. On this commit, I get the following backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f94de1 in CMSat::PackedRow::propGause (this=this@entry=0x7fffffffc780, tmp_clause=std::vector of length 0, capacity 8, 
    assigns=std::vector of length 6282, capacity 10224 = {...}, col_to_var=std::vector of length 113, capacity 128 = {...}, 
    GasVar_state=..., nb_var=@0x7fffffffc77c: 4294967295, start=4294967295)
    at /home/cipherboy/GitHub/msoos/cryptominisat/src/packedrow.cpp:134
134	    for (uint32_t i = start/64; i != size; i++) if (mp[i]) {
Missing separate debuginfos, use: dnf debuginfo-install boost-program-options-1.69.0-6.fc30.x86_64 libgcc-9.1.1-1.fc30.x86_64 libgomp-9.1.1-1.fc30.x86_64 libpng-1.6.36-1.fc30.x86_64 libstdc++-9.1.1-1.fc30.x86_64 m4ri-20140914-13.fc30.x86_64 zlib-1.2.11-15.fc30.x86_64
(gdb) backtrace
#0  0x00007ffff7f94de1 in CMSat::PackedRow::propGause (this=this@entry=0x7fffffffc780, 
    tmp_clause=std::vector of length 0, capacity 8, assigns=std::vector of length 6282, capacity 10224 = {...}, 
    col_to_var=std::vector of length 113, capacity 128 = {...}, GasVar_state=..., nb_var=@0x7fffffffc77c: 4294967295, 
    start=4294967295) at /home/cipherboy/GitHub/msoos/cryptominisat/src/packedrow.cpp:134
#1  0x00007ffff7f90f24 in CMSat::EGaussian::find_truths2 (this=0x53b230, i=i@entry=0x5c5fb0, j=@0x7fffffffc7f8: 0x5c5fb0, 
    p=p@entry=4578, row_n=16, gqd=...) at /usr/include/c++/9/bits/stl_vector.h:1040
#2  0x00007ffff7f401b1 in CMSat::Searcher::Gauss_elimination (this=0x4da490)
    at /home/cipherboy/GitHub/msoos/cryptominisat/build/cmsat5-src/cryptominisat5/solvertypesmini.h:65
#3  0x00007ffff7f48696 in CMSat::Searcher::search<false> (this=this@entry=0x4da490) at /usr/include/c++/9/bits/stl_vector.h:1040
#4  0x00007ffff7f4082e in CMSat::Searcher::solve (this=this@entry=0x4da490, _max_confls=<optimized out>, 
    upper_level_iteration_num=upper_level_iteration_num@entry=1) at /home/cipherboy/GitHub/msoos/cryptominisat/src/searcher.cpp:2252
#5  0x00007ffff7f5f575 in CMSat::Solver::iterate_until_solved (this=this@entry=0x4da490)
    at /home/cipherboy/GitHub/msoos/cryptominisat/src/solver.cpp:1665
#6  0x00007ffff7f5f9bc in CMSat::Solver::solve_with_assumptions (this=0x4da490, _assumptions=_assumptions@entry=0x0, 
    only_indep_solution=only_indep_solution@entry=false) at /home/cipherboy/GitHub/msoos/cryptominisat/src/solver.cpp:1432
#7  0x00007ffff7f9d67d in calc (assumptions=0x0, solve=<optimized out>, data=0x4da3d0, only_indep_solution=<optimized out>)
    at /home/cipherboy/GitHub/msoos/cryptominisat/src/cryptominisat.cpp:784
#8  0x000000000041c965 in Main::multi_solutions (this=0x7fffffffcc70) at /home/cipherboy/GitHub/msoos/cryptominisat/src/main.cpp:1260
#9  0x000000000041f4d5 in Main::solve (this=this@entry=0x7fffffffcc70) at /home/cipherboy/GitHub/msoos/cryptominisat/src/main.cpp:1232
#10 0x000000000041b66b in main (argc=2, argv=0x7fffffffd6e8) at /home/cipherboy/GitHub/msoos/cryptominisat/src/main_exe.cpp:46
(gdb) 
```

But I'll let @msoos take it from here. Guessing he'll know what the problem is better.

**Comment by msoos** [comment]
I suggest reading: http://www.whyprogramsfail.com/ It's the classic and will guide you to the right answer. The above is the easy (and wrong) analysis. The book is a classic, it's amazing, it's by a giant in the field. Highly recommended.

**Comment by maxzinkus** [comment]
Ok so as it happens that previous CNFXOR and output is a different bug. Attaching input, output, and CNFXOR for the double-free in EGaussian destructor

**Comment by maxzinkus** [comment]
[error.cnf.txt](https://github.com/msoos/cryptominisat/files/3159185/error.cnf.txt)
[stderr.txt](https://github.com/msoos/cryptominisat/files/3159186/stderr.txt)
[stdout.txt](https://github.com/msoos/cryptominisat/files/3159187/stdout.txt)

This repros single threaded with `cryptominsat5 error.cnf.txt`

**Comment by msoos** [comment]
Ah, finally fixed. Please try the "devel" branch. Both should now be fixed. Both seem to have the same root cause. Please validate and then close :)

**Comment by msoos** [comment]
Note that I have put Max's name in the commit to thank him :) Thanks again for the great input file, it helped me track this down quite quickly!

**Comment by maxzinkus** [comment]
@msoos Validated that the devel branch now correctly processes the CNFXORs :+1:
