### ISSUE TITLE
forward-incompatibility with setuptools

### ISSUE THREAD

**Issue by yoni-lavi** [msoos/cryptominisat#688]
https://github.com/msoos/cryptominisat/blob/a44df8b2f686d0b9d5a368a4c853279f7bafaafb/setup.py#L76

```
pip3 install pycryptosat
Collecting pycryptosat
  Using cached pycryptosat-0.6.1.tar.gz (285 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/43/7l85jz6s6359pg2gx1yw6nb00000gn/T/pip-install-tiyf54ms/pycryptosat_5d717caad5b94c168b200aba5a47b948/setup.py", line 154, in <module>
          sysconfig._init_posix = _init_posix(sysconfig._init_posix)
      AttributeError: module 'distutils.sysconfig' has no attribute '_init_posix'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

It turns out that this is a forward compatibility problem that pycryptosat has with setuptools, which I solved by downgrading it to 60.5.0.

**Comment by yoni-lavi** [comment]
looks like this was fixed by a PR that was merged in April

**Comment by msoos** [comment]
Glad to hear! :)

Mate
